"""Domain primitives shared by every SARANA service.

Pure types and helpers only - no I/O, no database, no HTTP.
"""

from sarana_shared.domain.admin import (
    AdminCodeError,
    AdminLevel,
    AdminUnit,
    District,
    DSDivision,
    GNDivision,
    Province,
    contains,
    district_of,
    ds_of,
    level_of,
    parent_code,
    validate_code,
)
from sarana_shared.domain.geo import (
    SRID_SLD99,
    SRID_WGS84,
    BoundingBox,
    GeoPoint,
    PointSource,
    haversine_m,
    in_sri_lanka,
)
from sarana_shared.domain.ids import (
    ensure_correlation_id,
    ensure_correlation_uuid,
    get_correlation_id,
    new_correlation_id,
    parse_correlation_id,
    set_correlation_id,
    short_code,
    uuid7,
    uuid7_timestamp,
)
from sarana_shared.domain.localised import (
    DEFAULT_LOCALE,
    REQUIRED_LOCALES,
    Locale,
    LocalisedText,
    TranslationCompleteness,
    check_completeness,
    parse_accept_language,
)
from sarana_shared.domain.money import (
    CURRENCY_CODE,
    CostScheduleVersion,
    LKRCents,
    Money,
    cents_to_rupees,
    format_lkr,
    rupees_to_cents,
)
from sarana_shared.domain.time import (
    COLOMBO,
    DisasterClock,
    ensure_utc,
    format_colombo,
    format_relative,
    parse_relative,
    to_colombo,
    utc_now,
)

__all__ = [
    "COLOMBO",
    "CURRENCY_CODE",
    "DEFAULT_LOCALE",
    "REQUIRED_LOCALES",
    "SRID_SLD99",
    "SRID_WGS84",
    "AdminCodeError",
    "AdminLevel",
    "AdminUnit",
    "BoundingBox",
    "CostScheduleVersion",
    "DSDivision",
    "DisasterClock",
    "District",
    "GNDivision",
    "GeoPoint",
    "LKRCents",
    "Locale",
    "LocalisedText",
    "Money",
    "PointSource",
    "Province",
    "TranslationCompleteness",
    "cents_to_rupees",
    "check_completeness",
    "contains",
    "district_of",
    "ds_of",
    "ensure_correlation_id",
    "ensure_correlation_uuid",
    "ensure_utc",
    "format_colombo",
    "format_lkr",
    "format_relative",
    "get_correlation_id",
    "haversine_m",
    "in_sri_lanka",
    "level_of",
    "new_correlation_id",
    "parent_code",
    "parse_accept_language",
    "parse_correlation_id",
    "parse_relative",
    "rupees_to_cents",
    "set_correlation_id",
    "short_code",
    "to_colombo",
    "utc_now",
    "uuid7",
    "uuid7_timestamp",
    "validate_code",
]
