// @ts-check
/**
 * Flat ESLint config for every TypeScript package in the workspace.
 *
 * Deliberately narrow: type-aware correctness rules and the import hygiene that keeps
 * the shared packages dependency-free in the right direction. Formatting is Prettier's
 * job and is not duplicated here.
 */
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/.expo/**',
      '**/coverage/**',
      // The Python virtualenv. Some site-packages ship JScript samples.
      '**/.venv/**',
      // Regenerated by `make openapi`; not ours to lint.
      'packages/ts-shared/src/api/generated.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Explicit is better than clever: this code gets a government IT review.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['error', { allow: ['warn', 'error'] }],
    },
  },
  {
    // Node scripts and tests print by design.
    files: ['**/scripts/**/*.ts', '**/*.test.ts', '**/*.test.tsx'],
    rules: { 'no-console': 'off' },
  },
  {
    // Build tooling that has to stay CommonJS for the bundler that reads it.
    files: ['**/*.config.js', '**/*.config.cjs', '**/babel.config.js'],
    languageOptions: {
      globals: { module: 'writable', require: 'readonly', __dirname: 'readonly' },
    },
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
);
