/**
 * Emits `tokens.css` and `tokens.nativewind.js` from `src/tokens`.
 *
 * Three consumers need the same numbers in three formats: the two Next.js apps read CSS
 * custom properties, the Expo app reads a NativeWind preset, and component code reads the
 * TypeScript directly. Hand-maintaining three tables guarantees they drift, and the way
 * that drift shows up is a severity colour that is right on web and wrong on the handset
 * a GN officer is holding.
 *
 * Both outputs are committed, so an app can import them without a build step.
 * `--check` regenerates into memory and diffs against what is on disk, which is what
 * `pnpm test:tokens-sync` runs: editing a token without regenerating fails CI.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { LOCALES, type Locale } from '@sarana/ts-shared/i18n';

import {
  DIVIDER,
  FOCUS_RING,
  INK,
  ON_FILL,
  ON_SIGNAL,
  PAPER,
  PENDING,
  SIGNAL,
  SURFACES,
  TEXT_ACCENT,
  VERIFY,
} from '../src/tokens/palette.js';
import { SEVERITY, SEVERITY_LEVELS } from '../src/tokens/severity.js';
import {
  EASING,
  FOCUS_RING_OFFSET,
  FOCUS_RING_WIDTH,
  MOTION,
  RADIUS,
  SHADOW,
  SPACE,
  TOUCH_TARGET_MIN,
  TOUCH_TARGET_SOS,
  Z_INDEX,
} from '../src/tokens/layout.js';
import {
  FONT_SANS,
  FONT_STACKS,
  LETTER_SPACING,
  LINE_HEIGHTS,
  SCRIPT_METRICS,
  TYPE_SCALE,
  lineHeightFor,
  sizeFor,
  type TypeSize,
} from '../src/tokens/typography.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = join(HERE, '..');

const BANNER = [
  '/*',
  ' * GENERATED by packages/ui/scripts/generate-tokens.ts. Do not edit.',
  ' *',
  ' * Source of truth: packages/ui/src/tokens/*.ts',
  ' * Regenerate:      pnpm --filter @sarana/ui tokens:generate',
  ' * Verify in CI:    pnpm --filter @sarana/ui test:tokens-sync',
  ' */',
].join('\n');

const SIZES = Object.keys(TYPE_SCALE) as TypeSize[];

/** The severity variables, written once per theme block. */
function severityVars(surface: 'dark' | 'light'): string[] {
  const lines: string[] = [];
  for (const level of SEVERITY_LEVELS) {
    const token = SEVERITY[level];
    const variant = token[surface];
    lines.push(
      `  --sev-${level}: ${token.base};`,
      `  --sev-${level}-bg: ${variant.bg};`,
      `  --sev-${level}-fg: ${variant.fg};`,
      `  --sev-${level}-border: ${variant.border};`,
    );
  }
  return lines;
}

function themeVars(surface: 'dark' | 'light'): string[] {
  const s = SURFACES[surface];
  return [
    `  --surface-base: ${s.base};`,
    `  --surface-raised: ${s.raised};`,
    `  --surface-card: ${s.card};`,
    `  --text-primary: ${s.text};`,
    `  --text-muted: ${s.muted};`,
    `  --text-accent: ${TEXT_ACCENT[surface]};`,
    `  --divider: ${DIVIDER[surface]};`,
    `  --focus-ring: ${FOCUS_RING[surface]};`,
    `  --verified: ${surface === 'dark' ? VERIFY[400] : VERIFY[500]};`,
    `  --pending: ${surface === 'dark' ? PENDING[400] : PENDING[500]};`,
    ...severityVars(surface),
  ];
}

function typeVarsFor(locale: Locale): string[] {
  const lines: string[] = [];
  for (const size of SIZES) {
    lines.push(`  --text-${size}: ${sizeFor(size, locale)}px;`);
    lines.push(`  --leading-${size}: ${lineHeightFor(size, locale)};`);
  }
  return lines;
}

function buildCss(): string {
  const blocks: string[] = [BANNER, ''];

  blocks.push(
    '/* Raw palette. Theme-independent: these are the values, not the roles. */',
    ':root {',
    ...Object.entries(INK).map(([step, hex]) => `  --ink-${step.padStart(3, '0')}: ${hex};`),
    ...Object.entries(PAPER).map(([step, hex]) => `  --paper-${step}: ${hex};`),
    ...Object.entries(SIGNAL).map(([step, hex]) => `  --signal-${step}: ${hex};`),
    ...Object.entries(VERIFY).map(([step, hex]) => `  --verify-${step}: ${hex};`),
    ...Object.entries(PENDING).map(([step, hex]) => `  --pending-${step}: ${hex};`),
    `  --on-fill: ${ON_FILL};`,
    `  --on-signal: ${ON_SIGNAL};`,
    '',
    '  /* Type. Overridden per script by the :lang() blocks below. */',
    `  --font-sans: ${FONT_SANS};`,
    `  --font-latin: ${FONT_STACKS.latin};`,
    `  --font-sinhala: ${FONT_STACKS.sinhala};`,
    `  --font-tamil: ${FONT_STACKS.tamil};`,
    `  --font-mono: ${FONT_STACKS.mono};`,
    ...typeVarsFor('en'),
    ...Object.entries(LETTER_SPACING).map(([size, value]) => `  --tracking-${size}: ${value};`),
    '',
    '  /* Space, radius, motion. */',
    ...Object.entries(SPACE).map(([step, px]) => `  --space-${step}: ${px}px;`),
    ...Object.entries(RADIUS).map(([name, px]) =>
      name === 'full' ? `  --radius-full: ${px}px;` : `  --radius-${name}: ${px}px;`,
    ),
    `  --motion-state: ${MOTION.state}ms;`,
    `  --motion-surface: ${MOTION.surface}ms;`,
    `  --ease-enter: ${EASING.enter};`,
    `  --ease-exit: ${EASING.exit};`,
    `  --shadow-raised: ${SHADOW.raised};`,
    `  --shadow-overlay: ${SHADOW.overlay};`,
    `  --focus-ring-width: ${FOCUS_RING_WIDTH}px;`,
    `  --focus-ring-offset: ${FOCUS_RING_OFFSET}px;`,
    `  --touch-target-min: ${TOUCH_TARGET_MIN}px;`,
    `  --touch-target-sos: ${TOUCH_TARGET_SOS}px;`,
    ...Object.entries(Z_INDEX).map(([name, value]) => `  --z-${name}: ${value};`),
    '}',
    '',
  );

  blocks.push(
    '/*',
    ' * Theme roles.',
    ' *',
    ' * The ops console is dark by default - operations rooms run dark, and a mid-range',
    ' * Android in the field saves real battery on an OLED panel. The public dashboard is',
    ' * light by default: it is read in daylight, screenshotted into articles, and printed.',
    ' * Both directions work in both apps; the defaults are chosen, not accidental.',
    ' *',
    ' * `[data-theme]` wins over the media query in both directions so an explicit choice',
    ' * is honoured on a device set the other way.',
    ' */',
    ':root,',
    '[data-theme=\'dark\'] {',
    ...themeVars('dark'),
    '}',
    '',
    '[data-theme=\'light\'] {',
    ...themeVars('light'),
    '}',
    '',
    '/* A surface that has not chosen: follow the device, but never override [data-theme]. */',
    '@media (prefers-color-scheme: light) {',
    '  :root:not([data-theme=\'dark\']) {',
    ...themeVars('light').map((rule) => `  ${rule}`),
    '  }',
    '}',
    '',
  );

  blocks.push(
    '/*',
    ' * Per-script metrics.',
    ' *',
    ' * Selection is automatic from the `lang` attribute. Nothing switches a font in',
    ' * JavaScript: a swap driven by a render pass flashes on every locale change and',
    ' * cannot work in a static export or on a printed page, and this dashboard is printed.',
    ' */',
  );
  for (const locale of LOCALES) {
    if (locale === 'en') continue;
    const metrics = SCRIPT_METRICS[locale];
    blocks.push(
      `:lang(${locale}) {`,
      `  --font-sans: ${metrics.stack};`,
      ...typeVarsFor(locale),
      '}',
      '',
    );
  }

  blocks.push(
    '/*',
    ' * Tracking is Latin-only. Sinhala and Tamil glyphs join and stack; letter-spacing',
    ' * breaks the join and renders words that a reader has to decode rather than read.',
    ' */',
    ':lang(si),',
    ':lang(ta) {',
    ...Object.keys(LETTER_SPACING).map((size) => `  --tracking-${size}: 0;`),
    '}',
    '',
  );

  blocks.push(
    '/*',
    ' * Motion means "something changed that you need to notice". None of it is',
    ' * load-bearing - no meaning in this system is carried only by a transition - so the',
    ' * reduced-motion branch is a flat zero rather than a substitute animation.',
    ' */',
    '@media (prefers-reduced-motion: reduce) {',
    '  :root {',
    '    --motion-state: 0ms;',
    '    --motion-surface: 0ms;',
    '  }',
    '',
    '  *,',
    '  *::before,',
    '  *::after {',
    '    animation-duration: 0.01ms !important;',
    '    animation-iteration-count: 1 !important;',
    '    transition-duration: 0.01ms !important;',
    '    scroll-behavior: auto !important;',
    '  }',
    '}',
    '',
  );

  blocks.push(
    '/*',
    ' * The Tailwind v4 theme bridge. `@theme inline` maps the variables above onto',
    ' * utility names, so `bg-surface-card` and `text-sev-3-fg` resolve to the same values',
    ' * the TypeScript exports - one table, three consumers.',
    ' */',
    '@theme inline {',
    '  --color-surface-base: var(--surface-base);',
    '  --color-surface-raised: var(--surface-raised);',
    '  --color-surface-card: var(--surface-card);',
    '  --color-text-primary: var(--text-primary);',
    '  --color-text-muted: var(--text-muted);',
    '  --color-text-accent: var(--text-accent);',
    '  --color-divider: var(--divider);',
    '  --color-focus-ring: var(--focus-ring);',
    '  --color-verified: var(--verified);',
    '  --color-pending: var(--pending);',
    '  --color-on-fill: var(--on-fill);',
    '  --color-on-signal: var(--on-signal);',
    ...Object.keys(SIGNAL).map((step) => `  --color-signal-${step}: var(--signal-${step});`),
    ...SEVERITY_LEVELS.flatMap((level) => [
      `  --color-sev-${level}: var(--sev-${level});`,
      `  --color-sev-${level}-bg: var(--sev-${level}-bg);`,
      `  --color-sev-${level}-fg: var(--sev-${level}-fg);`,
      `  --color-sev-${level}-border: var(--sev-${level}-border);`,
    ]),
    '  --font-sans: var(--font-sans);',
    '  --font-mono: var(--font-mono);',
    ...SIZES.map((size) => `  --text-${size}: var(--text-${size});`),
    ...SIZES.map((size) => `  --text-${size}--line-height: var(--leading-${size});`),
    ...Object.keys(RADIUS).map((name) => `  --radius-${name}: var(--radius-${name});`),
    '}',
    '',
  );

  blocks.push(
    '/*',
    ' * Every datum is mono with tabular figures: reference codes, LKR amounts,',
    ' * coordinates, timestamps, hashes, GN codes. Functional, not decorative - amounts',
    ' * have to align down a column and a hash has to be scannable character by character.',
    ' */',
    '[data-sarana-datum] {',
    '  font-family: var(--font-mono);',
    '  font-variant-numeric: tabular-nums;',
    '  font-feature-settings: \'tnum\' 1, \'zero\' 1;',
    '}',
    '',
    '/* The focus ring. Visible, 2px, offset, and never removed without a replacement. */',
    ':where(a, button, input, select, textarea, [tabindex]):focus-visible {',
    '  outline: var(--focus-ring-width) solid var(--focus-ring);',
    '  outline-offset: var(--focus-ring-offset);',
    '}',
    '',
  );

  return `${blocks.join('\n')}`;
}

function buildNativewind(): string {
  const table = {
    colors: {
      ink: Object.fromEntries(
        Object.entries(INK).map(([step, hex]) => [step.padStart(3, '0'), hex]),
      ),
      paper: PAPER,
      signal: SIGNAL,
      verify: VERIFY,
      pending: PENDING,
      onFill: ON_FILL,
      onSignal: ON_SIGNAL,
      divider: DIVIDER,
      focusRing: FOCUS_RING,
      textAccent: TEXT_ACCENT,
      surfaces: SURFACES,
      severity: Object.fromEntries(
        SEVERITY_LEVELS.map((level) => [
          level,
          {
            base: SEVERITY[level].base,
            shape: SEVERITY[level].shape,
            dark: SEVERITY[level].dark,
            light: SEVERITY[level].light,
          },
        ]),
      ),
    },
    fontFamily: {
      sans: FONT_SANS,
      latin: FONT_STACKS.latin,
      sinhala: FONT_STACKS.sinhala,
      tamil: FONT_STACKS.tamil,
      mono: FONT_STACKS.mono,
    },
    // Native has no `:lang()`, so the per-script table is exported whole and the native
    // Text component picks the row for the active locale. Same numbers, different seam.
    fontSize: Object.fromEntries(
      LOCALES.map((locale) => [
        locale,
        Object.fromEntries(
          SIZES.map((size) => [
            size,
            { size: sizeFor(size, locale), lineHeight: lineHeightFor(size, locale) },
          ]),
        ),
      ]),
    ),
    lineHeightBase: LINE_HEIGHTS,
    spacing: SPACE,
    borderRadius: RADIUS,
    motion: { ...MOTION, easing: EASING },
    touchTarget: { min: TOUCH_TARGET_MIN, sos: TOUCH_TARGET_SOS },
    zIndex: Z_INDEX,
  };

  return [
    BANNER,
    '',
    '/** @type {import(\'tailwindcss\').Config[\'theme\']} */',
    `export const saranaTokens = ${JSON.stringify(table, null, 2)};`,
    '',
    'export default saranaTokens;',
    '',
  ].join('\n');
}

interface Artefact {
  readonly path: string;
  readonly content: string;
}

function artefacts(): Artefact[] {
  return [
    { path: join(PACKAGE_ROOT, 'tokens.css'), content: buildCss() },
    { path: join(PACKAGE_ROOT, 'tokens.nativewind.js'), content: buildNativewind() },
  ];
}

function main(): void {
  const checking = process.argv.includes('--check');
  const stale: string[] = [];

  for (const artefact of artefacts()) {
    if (checking) {
      let onDisk: string;
      try {
        onDisk = readFileSync(artefact.path, 'utf8');
      } catch {
        stale.push(`${artefact.path} (missing)`);
        continue;
      }
      // Normalise line endings: the repo is developed on Windows and checked out on
      // Linux in CI, and a CRLF difference is not a token drift.
      if (onDisk.replace(/\r\n/g, '\n') !== artefact.content.replace(/\r\n/g, '\n')) {
        stale.push(artefact.path);
      }
    } else {
      writeFileSync(artefact.path, artefact.content, 'utf8');
      console.log(`wrote ${artefact.path}`);
    }
  }

  if (!checking) return;

  if (stale.length > 0) {
    console.error(
      'Generated token files are out of date with src/tokens. Run:\n' +
        '  pnpm --filter @sarana/ui tokens:generate\n\nStale:',
    );
    for (const path of stale) console.error(`  - ${path}`);
    process.exitCode = 1;
    return;
  }
  console.log('tokens.css and tokens.nativewind.js are in sync with src/tokens.');
}

main();
