"""Generated names are distributed the way the population actually is.

A demo where every household in Batticaloa has a Sinhala name is wrong, and it is wrong in
a way that tells Tamil and Muslim communities the system was not built with them in mind.
That failure is the same one the trilingual rule exists to prevent, and it shows up in test
data long before it shows up in a UI — which is why it is asserted here rather than noticed
in a screenshot.

The assertions are statistical and deliberately loose. A generator drawing from a weighted
distribution will not hit its weights exactly, and a test demanding it would fail on a
harmless change to the sampling. What these check is that each district's names come
predominantly from the right tradition, and — the assertion that actually matters — that no
district is generated entirely from one.
"""

from __future__ import annotations

import random
from collections import Counter

import pytest

from gov_mock.data.names import COMPOSITION, NameTradition, generate_name, tradition_for
from gov_mock.data.registry import households_for

SAMPLE = 4_000

# How far the drawn share may sit from the declared weight. Wide enough that the test is
# about the distribution being right rather than about the RNG being lucky.
TOLERANCE = 0.06


def _drawn(district_code: str, sample: int = SAMPLE) -> Counter[NameTradition]:
    rng = random.Random(20251128)  # noqa: S311 - test fixture, not a secret
    return Counter(tradition_for(district_code, rng) for _ in range(sample))


@pytest.mark.parametrize("district_code", sorted(COMPOSITION))
def test_each_district_draws_close_to_its_declared_weights(district_code: str) -> None:
    """The drawn share matches the declared composition, within tolerance."""
    counts = _drawn(district_code)
    expected = COMPOSITION[district_code]

    for tradition, share in zip(
        (NameTradition.SINHALA, NameTradition.TAMIL, NameTradition.MUSLIM), expected, strict=True
    ):
        drawn = counts[tradition] / SAMPLE
        assert abs(drawn - share) < TOLERANCE, (
            f"{district_code}: drew {drawn:.2%} {tradition.value}, declared {share:.2%}"
        )


@pytest.mark.parametrize(
    ("district_code", "expected"),
    [
        ("LK-41", NameTradition.TAMIL),  # Jaffna
        ("LK-51", NameTradition.TAMIL),  # Batticaloa
        ("LK-52", NameTradition.MUSLIM),  # Ampara
        ("LK-33", NameTradition.SINHALA),  # Hambantota
        ("LK-23", NameTradition.TAMIL),  # Nuwara Eliya
    ],
)
def test_the_predominant_tradition_is_the_right_one(
    district_code: str, expected: NameTradition
) -> None:
    """The most common naming convention in a district is the one that belongs there.

    These five are the districts a hand-written generator gets wrong: the north and east,
    Ampara's Muslim plurality, and Nuwara Eliya's Indian Tamil population. Hambantota is
    here as the control.
    """
    counts = _drawn(district_code)

    assert counts.most_common(1)[0][0] is expected


def test_no_district_is_generated_entirely_from_one_tradition() -> None:
    """Every district produces names from at least two traditions.

    The assertion that matters most. A district generated wholly from one tradition is a
    demo that erases the people who live there, and it is exactly what a lazy default —
    "Sinhala unless the district is in the north" — would produce.
    """
    for district_code in sorted(COMPOSITION):
        counts = _drawn(district_code, sample=1_000)
        present = {tradition for tradition, count in counts.items() if count > 0}
        assert len(present) >= 2, (
            f"{district_code} generated names from only {present}; every district in "
            "Sri Lanka is more mixed than that"
        )


def test_an_unknown_district_falls_back_to_an_island_average() -> None:
    """An unrecognised code does not silently default to the majority.

    Defaulting to Sinhala for anything the table does not cover is precisely the bug this
    module exists to prevent: it would be invisible, and it would be wrong in exactly the
    districts most likely to be added later.
    """
    counts = _drawn("LK-99")

    assert len({t for t, c in counts.items() if c > 0}) == 3


def test_names_follow_their_traditions_own_convention() -> None:
    """Each tradition is generated by its own rule, not one template with swapped words.

    Tamil naming is patronymic — an initial then the person's own name. Muslim names carry
    a religious first element. Generating all three as "given surname" would produce names
    that are recognisably wrong to anyone who reads them.
    """
    rng = random.Random(1)  # noqa: S311 - test fixture
    tamil = [generate_name("LK-41", rng) for _ in range(50)]
    assert all(name[1] == "." for name in tamil), "Tamil names must carry a patronymic initial"

    rng = random.Random(1)  # noqa: S311 - test fixture
    muslim = [generate_name("LK-52", rng) for _ in range(200)]
    prefixes = {"Mohamed", "Ahamed", "Abdul", "Fathima", "Nooranee"}
    assert any(name.split()[0] in prefixes for name in muslim)


def test_generated_households_are_mixed_in_a_mixed_district() -> None:
    """The distribution survives the whole way to a household record.

    Weights that are correct in the generator and lost by the time a household is built
    would pass every test above and still produce a monolingual register.
    """
    households = households_for("LK-51-01-001", seed=20251128)
    assert len(households) > 100

    patronymic = sum(1 for h in households if h.head_name[1] == ".")
    assert patronymic > len(households) * 0.5, "Batticaloa's register must be mainly Tamil"
    assert patronymic < len(households), "and not exclusively so"
