"""Alembic environment for incident-svc.

Runs against the async engine and restricts autogenerate to the schemas this service
owns (incident), so a migration here never proposes to drop another service's
tables just because they are absent from this metadata.
"""

from __future__ import annotations

import asyncio
import os
from logging.config import fileConfig
from pathlib import Path
from typing import Any

from alembic import context
from sqlalchemy import Connection, pool
from sqlalchemy.ext.asyncio import async_engine_from_config

# Importing the models package registers every table on Base.metadata.
import incident_svc.repo  # noqa: F401
from sarana_shared.db.base import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# Schemas this service owns outright. Anything outside them is another service's business
# and must never appear in an autogenerated migration.
OWNED_SCHEMAS: set[str] = {"incident"}

# The `outbox` schema is shared: every service owns exactly one table in it. Autogenerate
# must see this service's own outbox table and ignore the other four, or each service
# would propose dropping its neighbours' outboxes on every revision.
OUTBOX_SCHEMA = "outbox"

# Alembic's own bookkeeping. Kept outside every schema a migration creates, so
# `alembic downgrade base` can drop this service's schemas without RESTRICT
# refusing on the version table sitting inside one of them. One table per service
# keeps the five chains apart.
VERSION_SCHEMA = "migrations"
VERSION_TABLE = "alembic_version_incident_svc"
OWN_OUTBOX_TABLE = "incident_svc_event"


def include_object(
    obj: Any, name: str | None, type_: str, reflected: bool, compare_to: Any
) -> bool:
    """Restrict autogenerate to what this service owns."""
    schema = getattr(obj, "schema", None)
    if type_ == "table":
        if schema == OUTBOX_SCHEMA:
            return name == OWN_OUTBOX_TABLE
        return schema in OWNED_SCHEMAS

    parent = getattr(obj, "table", None)
    parent_schema = getattr(parent, "schema", None)
    if parent_schema == OUTBOX_SCHEMA:
        return getattr(parent, "name", None) == OWN_OUTBOX_TABLE
    return parent_schema in OWNED_SCHEMAS if parent_schema is not None else True


def _database_url() -> str:
    """Resolve the async DSN.

    An explicit environment variable always wins - that is how CI and the containers
    supply it. Falling back to the repository .env means `alembic upgrade head` also
    works when a developer runs it directly from this directory, rather than only
    through `make migrate`.
    """
    # Migrations create and alter objects, so they run as the owner. The application
    # connects as sarana_app and has no rights to do either.
    for name in ("SARANA_MIGRATION_DATABASE_URL", "SARANA_DATABASE_URL"):
        url = os.environ.get(name)
        if url:
            return url

    from dotenv import dotenv_values

    for parent in Path(__file__).resolve().parents:
        candidate = parent / ".env"
        if candidate.exists():
            values = dotenv_values(candidate)
            for name in ("SARANA_MIGRATION_DATABASE_URL", "SARANA_DATABASE_URL"):
                url = values.get(name)
                if url:
                    return url
            break

    raise RuntimeError(
        "Neither SARANA_MIGRATION_DATABASE_URL nor SARANA_DATABASE_URL is set, and no "
        ".env in any parent directory defines one. Alembic needs a DSN with owner "
        "rights to reach the database."
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live connection."""
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        include_schemas=True,
        include_object=include_object,
        version_table_schema=VERSION_SCHEMA,
        version_table=VERSION_TABLE,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    # The version schema has to exist before Alembic can record that a migration ran,
    # and it is deliberately not one this service's migrations create or drop.
    connection.exec_driver_sql(f'CREATE SCHEMA IF NOT EXISTS "{VERSION_SCHEMA}"')

    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_schemas=True,
        include_object=include_object,
        version_table_schema=VERSION_SCHEMA,
        version_table=VERSION_TABLE,
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Apply migrations against the live database."""
    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = _database_url()

    engine = async_engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)
    async with engine.connect() as connection:
        await connection.run_sync(do_run_migrations)
        # SQLAlchemy 2.0 has no autocommit: without this the whole migration, version
        # row included, rolls back when the connection closes. The failure is quiet -
        # Alembic reports "Running upgrade" and leaves the database untouched.
        await connection.commit()
    await engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
