"""Freeze the Ditwah scenario into a replay fixture the forecast agent can be tested on.

```bash
uv run python -m tools.seed.ditwah
```

## Why a file and not a live call

The headline claim of this platform is that Kandy's fragile slopes would have been flagged a
day before landfall. Build file 13 is explicit that this must be a test rather than a hope -
and a test that needs gov-mock running, Postgres up, core-api reachable and an OpenAI key is
a test that runs on a good day and nowhere else.

So the curve is generated once, committed, and replayed offline. The fixture is also
reviewable: somebody who doubts the claim can read the rainfall figures the agent was given
without running anything, which is not true of a live integration test.

## Why agent-svc does not import gov_mock

It would be one import and it would be wrong. gov-mock is a service that stands in for seven
government systems; a production agent that imports it has a dependency on the mock that
nobody notices until the real Met Department is wired in and the import is still there. The
fixture is the seam: this tool may read both, the agent reads neither.

The fixture is regenerated by running this module. It changes only when the mock's curve
changes, which is exactly when the test's expectations should be re-examined.
"""

from __future__ import annotations

import json
import re
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any, Final

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "services" / "gov-mock" / "src"))

from gov_mock.data import met as met_data  # noqa: E402
from gov_mock.data import nbro as nbro_data  # noqa: E402

OUT = REPO_ROOT / "data" / "fixtures" / "ditwah" / "replay.json"
SEED_DIR = REPO_ROOT / "data" / "seed" / "reference"

# The seed gov-mock runs the scenario at. Pinned so the fixture and a live `make up` demo
# tell the same story; changing it changes the weather.
SCENARIO_SEED: Final = 42

# Hours relative to landfall. Starts at T-72h because that is where `ditwah_kandy` starts -
# the three days in which anticipatory action is still possible, which is the only part of
# the story where a forecast can change an outcome.
OFFSETS: Final[tuple[int, ...]] = (-72, -60, -48, -36, -24, -12, 0, 12, 24)

FORECAST_WINDOWS: Final[tuple[int, ...]] = (24, 48, 72)

# A fixed instant for T+0, so a regenerated fixture differs only when the curve does. A
# `datetime.now()` here would produce a diff on every run and make the file impossible to
# review.
LANDFALL: Final = datetime(2026, 11, 28, 18, 0, tzinfo=UTC)

# The east coast, where Ditwah came ashore. Met issues Yellow against these alone before
# escalating nationally.
_POINT = re.compile(r"(-?\d+\.?\d*)\s+(-?\d+\.?\d*)")


def centroid_of(geom: str) -> tuple[float, float]:
    """The centre of a seeded division's rectangle.

    The database computes this with PostGIS and the seed file does not carry it. Averaging
    the ring's corners is exact for the rectangles the seed generates and close enough for
    anything else - and this is a fixture, not a responder's map.
    """
    points = [(float(lon), float(lat)) for lon, lat in _POINT.findall(geom)]
    if not points:
        return 0.0, 0.0
    # The last point repeats the first in a closed ring.
    ring = points[:-1] if len(points) > 1 and points[0] == points[-1] else points
    return (
        round(sum(lon for lon, _ in ring) / len(ring), 6),
        round(sum(lat for _, lat in ring) / len(ring), 6),
    )


def load_divisions() -> list[dict[str, Any]]:
    """Every seeded GN division, with the exposure attributes and a derived centroid."""
    divisions = json.loads((SEED_DIR / "gn_division.json").read_text(encoding="utf-8"))
    ds_divisions = json.loads((SEED_DIR / "ds_division.json").read_text(encoding="utf-8"))
    ds_code_by_id = {row["id"]: row["code"] for row in ds_divisions}

    rows = []
    for division in divisions:
        lon, lat = centroid_of(division["geom"])
        ds_code = ds_code_by_id.get(division["ds_division_id"], division["code"][:8])
        rows.append(
            {
                "gn_division_id": division["id"],
                "gn_division_code": division["code"],
                "ds_division_code": ds_code,
                "district_code": division["code"][:5],
                "centroid_lon": lon,
                "centroid_lat": lat,
                "household_count": division["household_count"],
                "population": division["population"],
                "landslide_zone": division["landslide_zone"],
                "flood_return_period_m": division["flood_return_period_m"],
                "road_access_class": division["road_access_class"],
                "cell_coverage_pct": division["cell_coverage_pct"],
                "elderly_pct": division["elderly_pct"],
                "under5_pct": division["under5_pct"],
                "name": division["name"],
            }
        )
    return rows


def snapshot(hours: float, districts: list[str]) -> dict[str, Any]:
    """Everything the feeds would have said at one point on the timeline."""
    now = LANDFALL + timedelta(hours=hours)

    observations = [
        {
            "station_id": station.station_id,
            "lon": station.lon,
            "lat": station.lat,
            "rainfall_mm_24h": met_data.rainfall_mm_24h(
                station, hours_since_landfall=hours, seed=SCENARIO_SEED
            ),
            "reporting": met_data.is_reporting(
                station, hours_since_landfall=hours, seed=SCENARIO_SEED
            ),
        }
        for station in met_data.STATIONS
    ]

    forecasts = {
        code: {
            str(window): met_data.district_rainfall_mm(
                code, hours_since_landfall=hours + window / 2, seed=SCENARIO_SEED
            )
            for window in FORECAST_WINDOWS
        }
        for code in districts
    }

    return {
        "hours_to_landfall": -hours,
        "now": now.isoformat(),
        "observations": observations,
        "district_forecasts": forecasts,
    }


def build() -> dict[str, Any]:
    divisions = load_divisions()
    districts = sorted({division["district_code"] for division in divisions})

    thresholds = {
        str(zone): {
            "zone": zone,
            "window_hours": threshold.window_hours,
            "watch_mm": threshold.watch_mm,
            "warning_mm": threshold.warning_mm,
            "evacuate_mm": threshold.evacuate_mm,
            "provenance": threshold.provenance,
        }
        for zone in (1, 2, 3, 4)
        for threshold in [nbro_data.threshold_for(zone)]
    }

    return {
        "scenario": "ditwah_kandy",
        "seed": SCENARIO_SEED,
        "landfall_at": LANDFALL.isoformat(),
        "generated_by": "tools/seed/ditwah.py",
        "note": (
            "Synthetic. Station names are real; every millimetre is generated by "
            "gov-mock's Ditwah curve. Regenerate with `uv run python -m tools.seed.ditwah` "
            "after any change to that curve, and re-read the forecast tests when you do."
        ),
        "districts": districts,
        "thresholds": thresholds,
        "divisions": divisions,
        "timeline": [snapshot(float(offset), districts) for offset in OFFSETS],
    }


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    fixture = build()
    OUT.write_text(
        json.dumps(fixture, ensure_ascii=False, indent=1, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    sys.stdout.write(
        f"wrote {OUT.relative_to(REPO_ROOT)}: "
        f"{len(fixture['divisions'])} divisions, {len(fixture['timeline'])} timeline points\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
