"""`python -m sarana_shared.openapi.merge` - build the merged OpenAPI spec.

The TypeScript client in `packages/ts-shared` is generated from one document, not six.
This script pulls `/openapi.json` from each running service and merges them, prefixing
component schema names with the service so two services can both define `Location`
without colliding.

Requires the stack to be up: `make up && make openapi`.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import httpx

# Service name -> local base URL. Mirrors the port map in the Makefile.
DEFAULT_SERVICES: dict[str, str] = {
    "core": "http://localhost:8001",
    "incident": "http://localhost:8002",
    "alerting": "http://localhost:8003",
    "ledger": "http://localhost:8004",
    "agent": "http://localhost:8005",
    "gov": "http://localhost:8006",
}

SPEC_VERSION = "3.1.0"


def _prefix_refs(node: Any, prefix: str) -> Any:
    """Rewrite every local `$ref` so component names carry the service prefix."""
    if isinstance(node, dict):
        return {
            key: (
                value.replace("#/components/schemas/", f"#/components/schemas/{prefix}")
                if key == "$ref" and isinstance(value, str)
                else _prefix_refs(value, prefix)
            )
            for key, value in node.items()
        }
    if isinstance(node, list):
        return [_prefix_refs(item, prefix) for item in node]
    return node


def fetch_spec(client: httpx.Client, base_url: str) -> dict[str, Any]:
    """Download one service's OpenAPI document."""
    response = client.get(f"{base_url.rstrip('/')}/openapi.json", timeout=10.0)
    response.raise_for_status()
    document: dict[str, Any] = response.json()
    return document


def merge(specs: dict[str, dict[str, Any]]) -> dict[str, Any]:
    """Merge per-service documents into one, prefixing component schema names."""
    merged: dict[str, Any] = {
        "openapi": SPEC_VERSION,
        "info": {
            "title": "SARANA API",
            "version": "1.0.0",
            "description": (
                "Merged specification across every SARANA service. Generated by "
                "`make openapi`; do not edit by hand."
            ),
        },
        "paths": {},
        "components": {"schemas": {}},
        "tags": [],
    }

    for service, document in sorted(specs.items()):
        prefix = f"{service.capitalize()}_"

        for path, operations in document.get("paths", {}).items():
            if path in merged["paths"]:
                raise ValueError(f"path collision on {path}: two services expose the same route")
            merged["paths"][path] = _prefix_refs(operations, prefix)

        schemas = document.get("components", {}).get("schemas", {})
        for name, schema in schemas.items():
            merged["components"]["schemas"][f"{prefix}{name}"] = _prefix_refs(schema, prefix)

        for tag in document.get("tags", []):
            if tag not in merged["tags"]:
                merged["tags"].append(tag)

    return merged


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="sarana-openapi-merge")
    parser.add_argument("--out", type=Path, required=True, help="Path to write the merged spec")
    parser.add_argument(
        "--service",
        action="append",
        metavar="NAME=URL",
        help="Override or add a service. Repeatable.",
    )
    args = parser.parse_args(argv)

    services = dict(DEFAULT_SERVICES)
    for override in args.service or []:
        name, _, url = override.partition("=")
        if not url:
            parser.error(f"--service expects NAME=URL, got {override!r}")
        services[name] = url

    specs: dict[str, dict[str, Any]] = {}
    with httpx.Client() as client:
        for name, base_url in services.items():
            try:
                specs[name] = fetch_spec(client, base_url)
            except (httpx.HTTPError, json.JSONDecodeError) as exc:
                sys.stderr.write(
                    f"could not read the OpenAPI document from {name} at {base_url}: {exc}\n"
                    "Is the stack up? Run `make up` first.\n"
                )
                return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(merge(specs), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    sys.stdout.write(f"merged {len(specs)} service specs into {args.out}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
